// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ammoIcon': string;
  'elementIcon': string;
  'weaponTypeIcon': string;
  'weaponTypeIconHeavy': string;
  'weaponTypeIconPrimary': string;
  'weaponTypeIconSpecial': string;
}
export const cssExports: CssExports;
export default cssExports;
